### PR TITLE
Fix how amorphous radiators in the goniometer are handled.

### PR DESCRIPTION
**Pull request by sdobbs**

### CODE REVIEW

**Comment by jrstevenjlab** [comment]
Is this related to Hovanes’s log entry https://logbooks.jlab.org/entry/3526966

**Comment by sdobbs** [comment]
This came about when I was looking into the problem described by that log entry, but is not directly related to it.  While it sounds like Hovanes fixed the EPICS side of things, there could be some old version of the RCDB being used for the DAQ - I'm not sure where it's located.

**Comment by jrstevenjlab** [comment]
Hi Sergey and Sasha,

Do you know where the RCDB version being used for the DAQ is located?  Who maintains that?

-Justin

**Comment by jrstevenjlab** [comment]
@sdobbs: Does the DAQ RCDB need to be updated with this change, since the latest was Jan 9?

**Comment by sdobbs** [comment]
Thanks for clarifying the location, I don't think the script is the cause
of the problem Hovanes reported.  We should keep an eye on this now that
there is a fix.

But yes, the DAQ RCDB should be updated with the latest change.

--Sean

**Pull request merged**
